config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  ActiveAdmin.routes(self)
  root to: "road_map#index"

  resources :boards
  resources :posts do
    put :start
    put :plan
    put :complete
    put :remove_milestone
    put :edit
  end
  resources :comments
  resources :votes
  resources :road_map

  delete :unset_current_user, to: "application#unset_current_user"

  get :slack_redirect, to: "application#slack_redirect"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :boards

  def name
    email
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :posts

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :board
  belongs_to :parent, optional: true, class_name: "Post"
  has_many :votes
  has_many :comments

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :votes
  has_many :comments
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_current_user

  def unset_current_user
    session[:user_id] = nil

    redirect_to road_map_index_path
  end

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def slack_redirect
    raw_response = Net::HTTP.get URI("https://slack.com/api/oauth.access?client_id=#{ENV["SLACK_CLIENT_ID"]}&client_secret=#{ENV["SLACK_CLIENT_SECRET"]}&code=#{params[:code]}&redirect_uri=#{slack_redirect_url}")
    response = JSON.parse(raw_response)

    user_slack_id = response["user"]["id"]
    user = User.find_or_create_by(slack_id: user_slack_id) do |u|
      u.name = response["user"]["name"]
      u.profile_picture = response["user"]["image_48"]
      u.thumbnail = response["user"]["image_32"]
    end
    session[:user_id] = user.id

    redirect_to road_map_index_path
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_current_user
  def show
    @boards = Hash[Board.all.pluck(:id, :title)]
    @posts = Board.find(params[:id]).posts
      .where.not("posts.status = (?)", "completed")
      .where("posts.title LIKE ? OR posts.short_description LIKE ?", "%#{params["search"]}%", "%#{params["search"]}%")
      .order(:status, created_at: :desc)
    @users = Hash[User.pluck(:id, :name)]
    all_voted_posts = Vote.distinct.pluck(:post_id)
    @vote_count = {}
    all_voted_posts.each do |p|
      @vote_count[p] = Vote.where("post_id = ?", p).count
    end
    if @current_user.present?
      @voted_posts = Vote.where(user_id: @current_user.id).pluck(:post_id)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new
    comment.assign_attributes(params.require(:comment).permit([
     :message,
     :post_id,
     :user_id
    ]))
#    authorize comment
    comment.save!

    redirect_back fallback_location: boards_path
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy!
    redirect_back fallback_location: boards_path
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  #before_action :authenticate_user!

  def index
    redirect_to Board.first
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_current_user

  def create
    post = Post.new
    post.assign_attributes(params.require(:post).permit([
     :title,
     :short_description,
     :description,
     :status,
     :board_id,
     :user_id
    ]))
#    authorize post
    post.save!
    Vote.create!(user_id: params[:post][:user_id], post_id: post.id)
    redirect_back fallback_location: boards_path
  end

  def show
    @boards = Board.all
    @post = Post.find(params[:id])
    @voters = User.joins(:votes).where("votes.post_id = ?", params[:id]).distinct.pluck(:name, :thumbnail)
    @comments = Comment.where(post_id: @post.id).order(created_at: :desc)
    @users = Hash[User.pluck(:id, :name)]
    @thumbnails = Hash[User.pluck(:id, :thumbnail)]
  end

  def new

  end

  def edit
    id =
      if params[:id].present?
        params[:id]
      else
        params[:post_id]
      end
    @boards = Board.all
    @post = Post.find(id)
    @voters = User.joins(:votes).where("votes.post_id = ?", id).distinct.pluck(:name, :thumbnail)
    @comments = Comment.where(post_id: @post.id).order(created_at: :desc)
    @users = Hash[User.pluck(:id, :name)]
    @thumbnails = Hash[User.pluck(:id, :thumbnail)]
    render 'edit'
  end

  def update
    post = Post.find(params[:id])
    post.update!(params.require(:post).permit(:status, :description, milestones: []))

    redirect_to post_path(id: params[:id])
  end

  def complete
    post = Post.find(params[:post_id])
    if post.milestones.include?("Done!")
      post.update!(status: 'completed')
    else
      post.update!(status: 'completed', milestones: post.milestones + [ "Done!"] )
    end

    redirect_back fallback_location: board_path(id: post.board_id)
  end

  def plan
    post = Post.find(params[:post_id])
    post.update!(status: 'planned', milestones: post.milestones - ["Done!"])

    redirect_back fallback_location: board_path(id: post.board_id)
  end

  def start
    post = Post.find(params[:post_id])
    if post.milestones.include?("Started")
      post.update!(status: 'in_progress', milestones: post.milestones - ["Done!"])
    else
      post.update!(status: 'in_progress', milestones: post.milestones + [ "Started"] - ["Done!"] )
    end

    redirect_back fallback_location: board_path(id: post.board_id)
  end

  def destroy
    post = Post.find(params[:id])
    board = post.board_id
    post.destroy!
    redirect_to board_url(id: board)
  end

end

app/controllers/road_map_controller.rb
class RoadMapController < ApplicationController
  before_action :set_current_user

  def show
  end

  def update
  end

  def index
    @boards = Board.all
  end

  def create
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    vote_try = Vote.find_by(post_id: params["vote"][:post_id], user_id: params["vote"][:user_id])
    if (vote_try.present?)
      Vote.destroy(vote_try.id)
    else

      vote = Vote.new
      vote.assign_attributes(params.require(:vote).permit([
       :post_id,
       :user_id
      ]))
  #    authorize vote
      vote.save!
    end

    redirect_back fallback_location: boards_path
  end

  def show

  end

  def new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def state_icon(state)
    case state
    when :planned
      "sticky-note"
    when :in_progress
      "wrench"
    when :completed
      "check"
    else
      "exclamation-circle"
    end
  end

  def state_color(state)
    case state
    when :planned
      "#1fa0ff"
    when :in_progress
      "#c17aff"
    when :completed
      "#6dd345"
    else
      "red"
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/road_map_helper.rb
module RoadMapHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/boards/show.html.slim
.nav.navbar role="navigation" aria-label="dropdown navigation"
  .container
    .navbar-brand
      a.navbar-item href="/road_map"
        img src=image_url('logo.png')
    .navbar-menu
      .navbar-start
        .field.navbar-item
          .control
            .select
              select onchange="location = this.value;"
                option disabled="" value=""
                  | -- Boards --
                - @boards.each do |id, board|
                  - if id == params[:id].to_i
                    option value="/boards/#{id}" selected=""
                      = board
                  - else
                    option value="/boards/#{id}"
                      = board

      = render partial: "layouts/nav"

.container
  #dashboard
    .sidebar
      .column
        .field
          .control
            div.header-row
              form.header-row
                div style="display:flex;align-items:center;"
                  = text_field_tag :search, params[:search], method: :post, class: "input", placeholder: "Search"
                  | &nbsp;&nbsp;
              form.header-row
                div style="display:flex;align-items:center;"
                  = button_to 'ok', method: :get, class: "button", params: {search: ""} do
                    = fa_icon "times"
        .card
          .card-header
            .card-header-title
              = "Request a feature"
          .card-content
            - if @current_user.present?
              = form_for Post.new do |f|
                .field
                  = f.hidden_field :board_id, value: params[:id]
                .field
                  = f.hidden_field :status, value: 'submitted'
                .field
                  = f.hidden_field :user_id, value: @current_user.id
                .field
                  = f.label :title, class: "label"
                  .control
                    = f.text_field :title, class: "input", required: true
                .field
                  = f.label :summary, class: "label"
                  .control
                    = f.text_field :short_description, class: "input"
                .field
                  = f.label :description, class: "label"
                  .control
                    = f.text_area :description, class: "textarea"
                .field
                  = f.submit "Send", class: "button",  style:  "width:100%;"
            - else
              br
              p.is-size-5
                | Login to request a feature

    .container.posts
      - if @posts.present?
        - @posts.each do |post|
          .columns
            .column.is-11
              = link_to post_path(post) do
                .card
                  .card-content.card-padding
                    .header-row
                      p.is-size-5
                        span
                          = "#{post.title} "
                      - if post.status == "completed"
                        span.tag style="background-color: #{state_color(:completed)}"
                          = "COMPLETED"
                      - elsif post.status == "in_progress"
                        span.tag style="background-color: #{state_color(:in_progress)}"
                          = "IN PROGRESS"
                      - elsif post.status == "planned"
                        span.tag style="background-color: #{state_color(:planned)}"
                          = "PLANNED"

                    p.is-size-6
                      = post.short_description
                  .card-content
                    .media
                      .media-left
                        figure.image.is-48x48
                          = image_tag post.user.profile_picture
                      .media-content
                        p.title.is-5
                          = post.user.name
                        p.subtitle.is-6
                          | #{distance_of_time_in_words(Time.now, post.created_at)} ago

            .column style="padding-top: 0px;"
              - if @current_user.present?
                - if @current_user.id != post.user_id
                  = form_for Vote.new do |f|
                    .field
                      = f.hidden_field :post_id, value: post.id
                    .field
                      = f.hidden_field :user_id, value: @current_user.id
                    .field
                      = button_tag(type: 'submit', class: "button is-size-2", id: 'validForm') do
                        .is-size-4 style="#{@voted_posts.include?(post.id) ? "color: #3273dc;" : ""}"
                          = fa_icon("thumbs-up")
                          br
                          = "#{@vote_count[post.id].present? ? "#{@vote_count[post.id]}" : "0"} "

              - if (!@current_user.present? || @current_user.id == post.user_id)
                .field
                .field
                .field
                  button.button.is-size-2
                    .is-size-4
                      = fa_icon("thumbs-up")
                      br
                      = "#{@vote_count[post.id].present? ? "#{@vote_count[post.id]}" : "0"} "

              - if @current_user.present? && @current_user.status == "admin"
                = button_to post, method: :delete, class: "button", style: "width:100%;", data: { confirm: 'Are you sure?' } do
                  = "Delete"

      - elsif Post.count == 0
        br
        br
        br
        br
        p.has-text-grey style="text-align: center;"
          | No feature requests here yet...

      - else
        br
        br
        br
        br
        p.has-text-grey style="text-align: center;"
          | No match found...

app/views/posts/_commentfield.html.slim
- if @current_user.present?
  = form_for Comment.new do |f|
    .field
      = f.hidden_field :post_id, value: params[:id]
    .field
      = f.hidden_field :user_id, value: @current_user.id
    .field
      = f.label :leave_a_comment, class: "label"
    .comment-field-row
      .control
        = f.text_area :message, class: "textarea", required: true
      .field style="text-align: right;"
        = f.submit "Send", class: "button", style: "padding-right: 4rem; padding-left: 4rem;"
- else
  p.is-size-6
    | Login to leave a comment
hr

app/views/posts/_comments.html.slim
- @comments.each do |comment|
  .column
    .card
      .card-content
        = comment.message
      footer.card-footer.header-row
        span
          div style="display:flex;align-items:center;"
            img src="#{@thumbnails[comment.user_id]}"
            p.footer-margins
              = @users[comment.user_id]
        span
          p.footer-margins
            | #{distance_of_time_in_words(Time.now, comment.created_at)} ago
        - if @current_user.present? && (@current_user.status == "admin" || comment.user_id == @current_user.id)
          span
            = button_to comment, method: :delete, class: "btn-link footer-margins" do
              = "Delete"

app/views/posts/_head.html.slim
.nav.navbar role="navigation" aria-label="dropdown navigation"
  .container
    .navbar-brand
      a.navbar-item href="/road_map"
        img src=image_url('logo.png')
    .navbar-menu
      .navbar-start
        a.navbar-item href="/road_map"
          | Road Map
        .field.navbar-item
          .control
            .select
              select onchange="location = this.value;"
                option disabled="" value=""
                  | -- Boards --
                - @boards.each do |board|
                  - if board.id == @post.board_id
                    option value="/boards/#{board.id}" selected=""
                      = @boards.find(board.id).title
                  - else
                    option value="/boards/#{board.id}"
                      = @boards.find(board.id).title


      = render partial: "layouts/nav"

app/views/posts/_sidebar.html.slim
.sidebar-in-post
  .column
    a href="/boards/#{@post.board_id}"
      = fa_icon "angle-left"
      = "  Back"
    br
    -if @post.milestones.present?
      hr style="width: 40%;"
      .is-size-5
        | Milestones
      ul
        .columns
          .column.is-9
            - if @current_user.present? && @current_user.status == "admin"
              = form_for @post, method: :put do |f|
                .field
                  = f.hidden_field :user_id, value: params[:id]
                  span
                    .control
                      - @post.milestones.each do |milestones|
                        = hidden_field_tag "post[milestones][]", milestones
                      = text_field_tag "post[milestones][]", "", class: "input", style: "width:100%;", required: true
                  span style="text-align:right;"
                    .field style="margin:auto;"
                      = button_tag(type: 'submit', class: "button", style: "width: 40%", id: 'validForm') do
                        = "Add"
        .columns
          .column.is-9
            - @post.milestones.each do |milestones|
              li
                div.header-row
                  div style="display:flex;align-items:center;"
                    = fa_icon "check"
                    | &nbsp;#{milestones}
                  div style="text-align: right;"
                    div
                      - if @current_user.present? && @current_user.status == "admin"
                        = link_to post_remove_milestone_path(post_id: @post.id, milestone: milestones), method: :put, class: "",  style: "cursor: pointer;" do
                          = fa_icon "times"
      br
    hr style="width: 40%;"
    .columns
      .column.is-9
        .is-size-5
          | Upvoted by
    ul
    .columns
      .column.is-9
        - @voters.each do |voter|
            div style="display:flex;align-items:center;"
              img src="#{voter[1]}"
              p
                | &nbsp;&nbsp;#{voter[0]}

app/views/posts/_title.html.slim
div style="display:flex;align-items:center;"
  span.is-size-2
    = "#{@post.title}"
    | &nbsp;&nbsp;
  - if @post.status == "completed"
    span.tag.is-size-5 style="background-color: #{state_color(:completed)}"
      = "COMPLETED"
  - elsif @post.status == "in_progress"
    span.tag.is-size-5 style="background-color: #{state_color(:in_progress)}"
      = "IN PROGRESS"
  - elsif @post.status == "planned"
    span.tag.is-size-5 style="background-color: #{state_color(:planned)}"
      = "PLANNED"

- if @current_user.present? && @current_user.status == "admin"
  .columns
    .column
      .header-row
        span.header-row
          - { planned: :plan, in_progress: :start, completed: :complete }.each do |state, action|
            = button_to send("post_#{action}_path", post_id: @post.id), method: :put, class: "button is-size-6", style: "background-color: #{state_color(state)}" do
              = t("states.#{state}")

        span.header-row
          - if @current_user.status == "admin"
            = button_to post_edit_path(post_id: @post.id), method: :put, class: "button has-background-white is-size-6", style: "margin-left: 5px; cursor: pointer;" do
              = "Edit"
            = button_to @post, method: :delete, class: "button has-background-white is-size-6", style: "margin-left: 5px; cursor: pointer;", data: { confirm: 'Are you sure?' } do
              = "Delete"


.header-row
  span
    .is-size-5
      = @post.created_at.strftime("%B %d, %Y")
  span
    div.header-row style="display:flex;align-items:center;"
      img src="#{User.find(@post.user_id).thumbnail}"
      .is-size-6
        | &nbsp;&nbsp;#{User.find(@post.user_id).name}
hr

app/views/posts/edit.html.slim
= render partial: "posts/head"
.container
  #posts
    = render partial: "posts/sidebar"
    .container.posts
      .column
        = render partial: "posts/title"
        .head-desc
          .is-size-4
            = @post.short_description
          br
          = form_for @post, method: :put do |f|
            .field
              = f.label :description, class: "label"
              .control
                = f.text_area :description, class: "textarea", value: @post.description
            .field
              = f.submit "Send", class: "button",  style:  "width:100%;"
            .field
              = button_to @post, method: :get, class: "button", style: "width:100%;" do
                = "Cancel"
        hr

      = render partial: "posts/comments"

app/views/posts/show.html.slim
= render partial: "posts/head"
.container
  #posts
    = render partial: "posts/sidebar"
    .container.posts
      .column
        = render partial: "posts/title"
        div
          .is-size-4
            = @post.short_description
          br
          p
            = @post.description
        hr
        = render partial: "posts/commentfield"

      = render partial: "posts/comments"

app/views/road_map/index.html.slim
.nav.navbar role="navigation" aria-label="dropdown navigation"
  .container
    .navbar-brand
      = link_to root_path, class: 'navbar-item' do
        = image_tag 'logo.png'
    .navbar-menu
      .navbar-start
        .field.navbar-item
          .control
            .select
              select onchange="location = this.value;"
                option disabled="" selected="" value=""
                  | -- Boards --
                - @boards.each do |board|
                    option value=board_path(board)
                      = board.title

      = render partial: "layouts/nav"

.container
  .columns
    - [ :planned, :in_progress, :completed ].each do |state|
      .column.is-4
        .has-text-centered.is-size-4
          span style="color: #{state_color(state)}"
            = fa_icon state_icon(state)
            | &nbsp;
          span
            = t("states.#{state}")

        .card
          .card-content
            ul
              - Post.where(status: state).includes(:board).each do |post|
                = link_to post_path(post), class: 'navbar-item'
                  li
                    div
                      span.is-size-5.is-uppercase.has-text-weight-bold
                          = post.board.title
                      span.is-size-5
                          = " - "
                          = post.title
                    p.is-size-6
                      = post.short_description